demo:
  host: http://localhost:3000
server:
  port: 3000
oAuth:
  github:
    clientId: 093de9694280c2258e0b
    clientSecret : 0484e4436bda5a391d519637795d631e4fe118c9
    userAuthorizationUri: https://github.com/login/oauth/authorize?
    accessTokenUri: https://github.com/login/oauth/access_token?
    resource:
        userInfoUri: https://api.github.com/user
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: root
    password:
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE